### ISSUE TITLE
lost the file R.layout.row_list_item and define of RowListItemBinding

### ISSUE THREAD

**Issue by spiderman16888** [naeemdev/Android-MVVM-DataBinding-RecyclerView-kotlin#1]
sorry, when I try to build it, it tell me:
error at lost these file:
com.androidmvvmdatabindingrecyclerviewkotlin.databinding.RowListItemBinding
and R.layout.row_list_item

override fun onCreateViewHolder(viewGroup: ViewGroup, i: Int): DeveloperViewHolder {
        val mDeveloperListItemBinding = DataBindingUtil.inflate<RowListItemBinding>(
            LayoutInflater.from(viewGroup.context),
            R.layout.row_list_item, viewGroup, false
        )

**Comment by naeemdev** [comment]
Hello thanks for your testing sure i will fix it and update

**Comment by naeemdev** [comment]
@spiderman16888 can you check it now
